# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb8d339e4d495c9df60d318c8042f95b5da5d6a56033be3667a3923e2c89376b4f1e8942e4a3f5bfbbd92aee77e9f3f0ae69927e64f4753de85d018a024e5102

test:
  secret_key_base: 048af257bcac117bb78575082fe265e945efc7745090a442200c21c3544c6b3ed6797f224ca0d7f84cdea0aa6186775d7de1f3a9e70b4b299c7fcc4c6910b365

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
